sender_email = automaticmail871@gmail.com 
password = Test@123
sender.password = ofwv pqny mclo qxzn
receiver_email = pavithrajaya7200@gmail.com
amazon_url = https://www.amazon.in/dp/
excel_file = src/main/resources/product_list.xlsx
report_file = src/main/resources/priceReport.xlsx
dashboard_file = src/main/resources/dashboard.html
telegram_token = 8941495132:AAG3qWUCEZjgh_HMGEGmSwZ-9_lE6cJ9zEM
telegram_chatid = 1219405250